// components/nav.vue
<template>
  <nav class="navbar">
    <div class="navbar-brand is-size-4">
      <nuxt-link to="/" class="navbar-item navbar-logo">
        <span class="runebase-icon runebase-icon--runebase" /> explorer.runebase.io
      </nuxt-link>
      <button type="button" class="button navbar-burger" @click="showMenu = !showMenu">
        <span></span><span></span><span></span>
      </button>
    </div>
    <div class="navbar-menu" :class="{'is-active': showMenu}">
      <div class="navbar-start is-uppercase">
        <AttributeInjector class="navbar-item" @click.native="showMenu = !showMenu">
          <nuxt-link to="/block">{{ $tc('blockchain.block', 2) }}</nuxt-link>
          <nuxt-link to="/contract/tokens">{{ $tc('blockchain.token') }}</nuxt-link>
          <div class="has-dropdown is-hoverable">
            <nuxt-link to="/misc/charts" class="navbar-link">{{ $t('misc.misc') }}</nuxt-link>
            <div class="navbar-dropdown is-boxed">
              <nuxt-link to="/misc/charts" class="navbar-item">
                {{ $t('misc.charts_title') }}
              </nuxt-link>
              <nuxt-link to="/misc/rich-list" class="navbar-item">
                {{ $t('misc.rich_list_title') }}
              </nuxt-link>
              <nuxt-link to="/misc/biggest-miners" class="navbar-item">
                {{ $t('misc.biggest_miners_title') }}
              </nuxt-link>
              <nuxt-link to="/misc/stake-calculator" class="navbar-item">
                {{ $t('misc.stake_calculator.title') }}
              </nuxt-link>
              <nuxt-link to="/misc/raw-tx" class="navbar-item">
                Send Raw Transaction
              </nuxt-link>
            </div>
          </div>
        </AttributeInjector>
      </div>
      <form class="navbar-end" @submit.prevent="search">
        <div class="navbar-item input-item">
          <input type="text" class="input" v-model="searchString" :placeholder="$t('nav.search')">
          <button type="submit" class="button is-runebase" :class="{'is-loading': searching}">
            <Icon icon="search" />
          </button>
        </div>
      </form>
    </div>
  </nav>
</template>

<script>
  import {get as runebaseinfoGet} from '@/services/runebaseinfo-api'

  export default {
    data() {
      return {
        showMenu: false,
        searchString: '',
        searching: false
      }
    },
    methods: {
      async search() {
        let searchString = this.searchString.trim()
        if (!searchString || this.searching) {
          return
        }
        this.searching = true
        try {
          let {type, id, address} = await runebaseinfoGet(`/search`, {params: {query: searchString}})
          switch (type) {
          case 'address':
            this.searchString = ''
            this.$router.push(`/address/${searchString}`)
            break
          case 'block':
            this.searchString = ''
            this.$router.push(`/block/${searchString}`)
            break
          case 'contract':
            this.searchString = ''
            if (address) {
              this.$router.push(`/contract/${address}`)
            } else {
              this.$router.push(`/contract/${searchString}`)
            }
            break
          case 'transaction':
            this.searchString = ''
            this.$router.push(`/tx/${searchString}`)
            break
          }
        } catch (err) {}
        this.showMenu = false
        this.searching = false
      }
    }
  }
</script>

<style lang="less" scoped>
  .navbar-logo {
    display: inline-block;
    .runebase-icon {
      vertical-align: middle;
    }
  }
  .navbar-end {
    flex: auto;
    align-items: center;
    .navbar-item {
      flex: auto;
      position: relative;
      input {
        padding-right: 3em;
      }
      button {
        position: absolute;
        top: 0.5em;
        right: 0;
      }
    }
  }
</style>

// src/components/Nav.jsx
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { get as runebaseinfoGet } from '@/services/runebaseinfo-api'
import Icon from './Icon'

export default function Nav() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [showMenu, setShowMenu] = useState(false)
  const [searchString, setSearchString] = useState('')
  const [searching, setSearching] = useState(false)

  async function search(e) {
    e.preventDefault()
    let query = searchString.trim()
    if (!query || searching) return
    setSearching(true)
    try {
      let { type, address } = await runebaseinfoGet('/search', { params: { query } })
      switch (type) {
        case 'address':
          setSearchString('')
          navigate(`/address/${query}`)
          break
        case 'block':
          setSearchString('')
          navigate(`/block/${query}`)
          break
        case 'contract':
          setSearchString('')
          navigate(`/contract/${address || query}`)
          break
        case 'transaction':
          setSearchString('')
          navigate(`/tx/${query}`)
          break
      }
    } catch (err) {}
    setShowMenu(false)
    setSearching(false)
  }

  return (
    <nav className="navbar">
      <div className="navbar-brand is-size-4">
        <Link to="/" className="navbar-item navbar-logo">
          <span className="runebase-icon runebase-icon--runebase" /> explorer.runebase.io
        </Link>
        <button type="button" className="button navbar-burger" onClick={() => setShowMenu(!showMenu)}>
          <span></span><span></span><span></span>
        </button>
      </div>
      <div className={`navbar-menu ${showMenu ? 'is-active' : ''}`}>
        <div className="navbar-start is-uppercase">
          <Link to="/block" className="navbar-item" onClick={() => setShowMenu(false)}>
            {t('blockchain.block_plural')}
          </Link>
          <Link to="/contract/tokens" className="navbar-item" onClick={() => setShowMenu(false)}>
            {t('blockchain.token')}
          </Link>
          <div className="navbar-item has-dropdown is-hoverable">
            <Link to="/misc/charts" className="navbar-link">{t('misc.misc')}</Link>
            <div className="navbar-dropdown is-boxed">
              <Link to="/misc/charts" className="navbar-item" onClick={() => setShowMenu(false)}>
                {t('misc.charts_title')}
              </Link>
              <Link to="/misc/rich-list" className="navbar-item" onClick={() => setShowMenu(false)}>
                {t('misc.rich_list_title')}
              </Link>
              <Link to="/misc/biggest-miners" className="navbar-item" onClick={() => setShowMenu(false)}>
                {t('misc.biggest_miners_title')}
              </Link>
              <Link to="/misc/stake-calculator" className="navbar-item" onClick={() => setShowMenu(false)}>
                {t('misc.stake_calculator.title')}
              </Link>
              <Link to="/misc/raw-tx" className="navbar-item" onClick={() => setShowMenu(false)}>
                Send Raw Transaction
              </Link>
            </div>
          </div>
        </div>
        <form className="navbar-end" onSubmit={search} style={{ flex: 'auto', alignItems: 'center' }}>
          <div className="navbar-item" style={{ flex: 'auto', position: 'relative' }}>
            <input
              type="text"
              className="input"
              value={searchString}
              onChange={e => setSearchString(e.target.value)}
              placeholder={t('nav.search')}
              style={{ paddingRight: '3em' }}
            />
            <button
              type="submit"
              className={`button is-runebase ${searching ? 'is-loading' : ''}`}
              style={{ position: 'absolute', top: '0.5em', right: 0 }}
            >
              <Icon icon="search" />
            </button>
          </div>
        </form>
      </div>
    </nav>
  )
}
