// src/pages/misc/BiggestMiners.jsx
import React, { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useSelector } from 'react-redux'
import { useTranslation } from 'react-i18next'
import { formatRunebase } from '@/utils/format'
import MiscModel from '@/models/misc'
import Pagination from '@/components/Pagination'
import AddressLink from '@/components/links/AddressLink'

export default function BiggestMiners() {
  const { t } = useTranslation()
  const [searchParams] = useSearchParams()
  const blockchain = useSelector(state => state.blockchain)
  const [totalCount, setTotalCount] = useState(0)
  const [list, setList] = useState([])
  const currentPage = Number(searchParams.get('page') || 1)
  const pages = Math.ceil(totalCount / 100)
  const posBlocks = blockchain.height - 5000

  useEffect(() => {
    document.title = t('misc.biggest_miners_title') + ' - explorer.runebase.io'
    MiscModel.biggestMiners({ from: (currentPage - 1) * 100, to: currentPage * 100 })
      .then(({ totalCount: tc, list: l }) => { setTotalCount(tc); setList(l) })
      .catch(() => {})
  }, [currentPage])

  function getLink(page) { return `/misc/biggest-miners?page=${page}` }

  return (
    <section className="container">
      {pages > 1 && <Pagination pages={pages} currentPage={currentPage} getLink={getLink} />}
      <table className="table is-fullwidth is-bordered is-striped" style={{ marginTop: '0.5rem', marginBottom: '0.5rem' }}>
        <thead>
          <tr>
            <th>{t('misc.ranking')}</th>
            <th>{t('misc.address')}</th>
            <th>{t('misc.blocks_mined')}</th>
            <th>{t('misc.percentage')}</th>
            <th className="is-hidden-touch">{t('misc.balance')}</th>
          </tr>
        </thead>
        <tbody>
          {list.map(({ address, blocks, balance }, index) => (
            <tr key={address}>
              <td>{100 * (currentPage - 1) + index + 1}</td>
              <td><AddressLink address={address} /></td>
              <td>{blocks}</td>
              <td className="monospace">{(blocks / posBlocks * 100).toFixed(4)}%</td>
              <td className="monospace is-hidden-touch">{formatRunebase(balance, 8)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {pages > 1 && <Pagination pages={pages} currentPage={currentPage} getLink={getLink} />}
    </section>
  )
}

// pages/misc/biggest-miners.vue
<template>
  <section class="container" ref="section">
    <Pagination v-if="pages > 1" :pages="pages" :currentPage="currentPage" :getLink="getLink" />
    <table class="table is-fullwidth is-bordered is-striped">
      <thead>
        <tr>
          <th>{{ $t('misc.ranking') }}</th>
          <th>{{ $t('misc.address') }}</th>
          <th>{{ $t('misc.blocks_mined') }}</th>
          <th>{{ $t('misc.percentage') }}</th>
          <th class="is-hidden-touch">{{ $t('misc.balance') }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="({address, blocks, balance}, index) of list">
          <td>{{ 100 * (currentPage - 1) + index + 1 }}</td>
          <td>
            <AddressLink :address="address" />
          </td>
          <td>{{ blocks }}</td>
          <td class="monospace">{{ (blocks / posBlocks * 100).toFixed(4) + '%' }}</td>
          <td class="monospace is-hidden-touch">{{ balance | runebase(8) }}</td>
        </tr>
      </tbody>
    </table>
    <Pagination v-if="pages > 1" :pages="pages" :currentPage="currentPage" :getLink="getLink" />
  </section>
</template>

<script>
  import Misc from '@/models/misc'
  import {RequestError} from '@/services/runebaseinfo-api'
  import {scrollIntoView} from '@/utils/dom'

  export default {
    head() {
      return {
        title: this.$t('misc.biggest_miners_title')
      }
    },
    data() {
      return {
        totalCount: 0,
        list: [],
        currentPage: Number(this.$route.query.page || 1)
      }
    },
    async asyncData({req, query, redirect, error}) {
      try {
        if (query.page && !/^[1-9]\d*$/.test(query.page)) {
          redirect('/misc/biggest-miners')
        }
        let page = Number(query.page || 1)
        let {totalCount, list} = await Misc.biggestMiners(
          {from: (page - 1) * 100, to: page * 100},
          {ip: req && req.ip}
        )
        if (page > 1 && totalCount <= (page - 1) * 100) {
          redirect('/misc/biggest-miners', {page: Math.ceil(totalCount / 100)})
        }
        return {totalCount, list}
      } catch (err) {
        if (err instanceof RequestError) {
          error({statusCode: err.code, message: err.message})
        } else {
          error({statusCode: 500, message: err.message})
        }
      }
    },
    computed: {
      blockchain() {
        return this.$store.state.blockchain
      },
      posBlocks() {
        return this.blockchain.height - 5000
      },
      pages() {
        return Math.ceil(this.totalCount / 100)
      }
    },
    methods: {
      getLink(page) {
        return {name: 'misc-biggest-miners', query: {page}}
      }
    },
    async beforeRouteUpdate(to, from, next) {
      let page = Number(to.query.page || 1)
      let {totalCount, list} = await Misc.biggestMiners({from: (page - 1) * 100, to: page * 100})
      this.totalCount = totalCount
      if (page > this.pages && this.pages > 1) {
        this.$router.push({name: 'misc-biggest-miners', query: {page: Math.ceil(totalCount / 100)}})
        return
      }
      this.list = list
      this.currentPage = page
      next()
      scrollIntoView(this.$refs.section)
    }
  }
</script>

<style scoped>
  .table {
    margin-top: 0.5rem;
    margin-bottom: 0.5rem;
  }
</style>
