// src/pages/misc/StakeCalculator.jsx
import React, { useState, useEffect } from 'react'
import { useSelector } from 'react-redux'
import { useTranslation } from 'react-i18next'
import { useWebSocket } from '@/hooks/useWebSocket'
import { formatRunebase } from '@/utils/format'
import { toHexAddress } from '@/utils/address'
import Address from '@/models/address'
import MiscModel from '@/models/misc'

export default function StakeCalculator() {
  const { t } = useTranslation()
  const blockchain = useSelector(state => state.blockchain)
  const { subscribe, unsubscribe } = useWebSocket()
  const [netStakeWeight, setNetStakeWeight] = useState(0)
  const [address, setAddress] = useState('')
  const [weightInput, setWeightInput] = useState('')

  useEffect(() => {
    document.title = t('misc.stake_calculator.title') + ' - explorer.runebase.io'
    MiscModel.info().then(({ netStakeWeight: w }) => setNetStakeWeight(w)).catch(() => {})

    const onWeight = (w) => setNetStakeWeight(w)
    subscribe('blockchain', 'stakeweight', onWeight)
    return () => unsubscribe('blockchain', 'stakeweight', onWeight)
  }, [])

  useEffect(() => {
    if (!address) return
    const addresses = address.split(',')
    try {
      if (addresses.every(toHexAddress)) {
        Address.get(address).then(({ balance }) => {
          setWeightInput((balance / 1e8).toFixed(8))
        }).catch(() => {})
      }
    } catch (err) {}
  }, [address])

  const weight = Math.round(Number(weightInput.replace(',', '')) * 1e8) || 0
  const n = 8
  const p = weight ? 1 - Math.exp(-weight / (n * netStakeWeight)) : 0
  const expectedTime = weight ? n * 16 * (1 / n - p * p) / (p - p * p) : 0

  let interval = ''
  if (expectedTime < 60) interval = expectedTime.toFixed(2) + ' ' + t('misc.stake_calculator.seconds')
  else if (expectedTime < 3600) interval = (expectedTime / 60).toFixed(2) + ' ' + t('misc.stake_calculator.minutes')
  else if (expectedTime < 86400) interval = (expectedTime / 3600).toFixed(2) + ' ' + t('misc.stake_calculator.hours')
  else if (expectedTime < 86400 * 30) interval = (expectedTime / 86400).toFixed(2) + ' ' + t('misc.stake_calculator.days')
  else if (expectedTime < 86400 * 360) interval = (expectedTime / 86400 / 30).toFixed(2) + ' ' + t('misc.stake_calculator.months')
  else interval = (expectedTime / 86400 / 365).toFixed(2) + ' ' + t('misc.stake_calculator.years')

  const reward = 100e8

  return (
    <form onSubmit={e => e.preventDefault()}>
      <div className="field">
        <label>{t('blockchain.network_weight')}</label>
        <div className="control"><output className="monospace">{formatRunebase(netStakeWeight, 8)}</output></div>
      </div>
      <div className="field">
        <label>{t('misc.stake_calculator.enter_address')}</label>
        <div className="control">
          <input type="text" className="input monospace" value={address} onChange={e => setAddress(e.target.value)} />
        </div>
      </div>
      <div className="field">
        <label>{t('misc.stake_calculator.weight')}</label>
        <div className="control">
          <input type="number" className="input monospace" value={weightInput} onChange={e => setWeightInput(e.target.value)} placeholder="0" />
        </div>
      </div>
      {weight > 0 && (
        <>
          <div className="field">
            <label>{t('misc.stake_calculator.expected_time')}</label>
            <div className="control"><output>{interval}</output></div>
          </div>
          {expectedTime < 100000 && (
            <div className="field">
              <label>{t('misc.stake_calculator.average_blocks_per_day')}</label>
              <div className="control"><output>{(86400 / expectedTime).toFixed(2)}</output></div>
            </div>
          )}
          <div className="field">
            <label>{t('misc.stake_calculator.average_blocks_per_year')}</label>
            <div className="control"><output>{(365 * 86400 / expectedTime).toFixed(2)}</output></div>
          </div>
        </>
      )}
      <div className="field">
        <label>{t('misc.stake_calculator.yearly_roi')}</label>
        <div className="control">
          <output className="monospace">{netStakeWeight ? (reward * 365 * 675 / netStakeWeight * 100).toFixed(2) : 0}%</output>
        </div>
      </div>
    </form>
  )
}

// pages/misc/stake-calculator.vue
<template>
  <form @submit.prevent>
    <div class="field">
      <label>{{ $t('blockchain.network_weight') }}</label>
      <div class="control">
        <output class="monospace">{{ netStakeWeight | runebase(8) }}</output>
      </div>
    </div>
    <div class="field">
      <label>{{ $t('misc.stake_calculator.enter_address') }}</label>
      <div class="control">
        <input type="text" class="input monospace" v-model="address">
      </div>
    </div>
    <div class="field">
      <label>{{ $t('misc.stake_calculator.weight') }}</label>
      <div class="control">
        <input type="number" class="input monospace" v-model="weightInput" placeholder="0">
      </div>
    </div>
    <template v-if="weight">
      <div class="field">
        <label>{{ $t('misc.stake_calculator.expected_time') }}</label>
        <div class="control">
          <output>{{ interval }}</output>
        </div>
      </div>
      <div v-if="expectedTime < 100000" class="field">
        <label>{{ $t('misc.stake_calculator.average_blocks_per_day' )}}</label>
        <div class="control">
          <output>{{ (86400 / expectedTime).toFixed(2) }}</output>
        </div>
      </div>
      <div class="field">
        <label>{{ $t('misc.stake_calculator.average_blocks_per_year' )}}</label>
        <div class="control">
          <output>{{ (365 * 86400 / expectedTime).toFixed(2) }}</output>
        </div>
      </div>
    </template>
    <div class="field">
      <label>{{ $t('misc.stake_calculator.yearly_roi') }}</label>
      <div class="control">
        <output class="monospace">
          {{ (reward * 365 * 675 / this.netStakeWeight * 100).toFixed(2) }}%
        </output>
      </div>
    </div>
  </form>
</template>

<script>
  import {toHexAddress} from '@/utils/address'
  import Address from '@/models/address'
  import Misc from '@/models/misc'
  import {RequestError} from '@/services/runebaseinfo-api'

  export default {
    head() {
      return {
        title: this.$t('misc.stake_calculator.title')
      }
    },
    data() {
      return {
        netStakeWeight: 0,
        address: '',
        weightInput: '',
      }
    },
    async asyncData({req, error}) {
      try {
        let {netStakeWeight} = await Misc.info({ip: req && req.ip})
        return {netStakeWeight}
      } catch (err) {
        if (err instanceof RequestError) {
          error({statusCode: err.code, message: err.message})
        } else {
          error({statusCode: 500, message: err.message})
        }
      }
    },
    computed: {
      blockchain() {
        return this.$store.state.blockchain
      },
      weight() {
        return Math.round(Number(this.weightInput.replace(',')) * 1e8) || 0
      },
      expectedTime() {
        const n = 8
        let p = 1 - Math.exp(-this.weight / (n * this.netStakeWeight))
        return n * 16 * (1 / n - p * p) / (p - p * p)
      },
      interval() {
        if (this.expectedTime < 60) {
          return this.expectedTime.toFixed(2) + ' ' + this.$t('misc.stake_calculator.seconds')
        } else if (this.expectedTime < 60 * 60) {
          return (this.expectedTime / 60).toFixed(2) + ' ' + this.$t('misc.stake_calculator.minutes')
        } else if (this.expectedTime < 60 * 60 * 24) {
          return (this.expectedTime / 60 / 60).toFixed(2) + ' ' + this.$t('misc.stake_calculator.hours')
        } else if (this.expectedTime < 60 * 60 * 24 * 30) {
          return (this.expectedTime / 60 / 60 / 24).toFixed(2) + ' ' + this.$t('misc.stake_calculator.days')
        } else if (this.expectedTime < 60 * 60 * 24 * 360) {
          return (this.expectedTime / 60 / 60 / 24 / 30).toFixed(2) + ' ' + this.$t('misc.stake_calculator.months')
        } else {
          return (this.expectedTime / 60 / 60 / 24 / 365).toFixed(2) + ' ' + this.$t('misc.stake_calculator.years')
        }
      },
      reward() {
        return 100e8
      }
    },
    watch: {
      async address() {
        let addresses = this.address.split(',')
        try {
          if (addresses.every(toHexAddress)) {
            let {balance} = await Address.get(this.address)
            this.weightInput = (balance / 1e8).toFixed(8)
          } else {
            this.weightInput = ''
          }
        } catch (err) {
          if (!(err instanceof RequestError)) {
            throw err
          }
        }
      }
    },
    methods: {
      onStakeWeight(stakeWeight) {
        this.netStakeWeight = stakeWeight
      }
    },
    mounted() {
      this._onStakeWeight = this.onStakeWeight.bind(this)
      this.$subscribe('blockchain', 'stakeweight', this._onStakeWeight)
    },
    beforeDestroy() {
      this.$unsubscribe('blockchain', 'stakeweight', this._onStakeWeight)
    }
  }
</script>
